#! /usr/bin/bash
exe=`realpath "$0"`
dir=`dirname "$exe"`
cd "$dir"
for ver in 1.{6..11}; do
    echo "############## julia-$ver"
    rm -f Manifest.toml
    test -r ".Manifest-$ver.toml" && cp -pf ".Manifest-$ver.toml" Manifest.toml
    julia +"$ver" --check-bounds=yes --depwarn=yes --color=yes \
        -e 'import Pkg;
            # Add "extra" dependencies globally.
            #Pkg.add("DataFrames");
            # Activate project and "develop" unregistered dependencies.
            Pkg.activate(pwd());
            Pkg.develop(url = "https://github.com/emmt/FITSHeaders.jl");
            Pkg.resolve();
            Pkg.build("EasyFITS");
            include("test/runtests.jl");'
    test -r Manifest.toml && mv -f Manifest.toml ".Manifest-$ver.toml"
done
