#! /bin/sh

dir=$(dirname "$0")
cd "$dir/.."
test -e Manifest.toml || julia --startup-file=no --project=docs/ -e \
    'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
exec julia --startup-file=no --color=yes --project=docs/ docs/make.jl
